# Dependabot configuration for LevelUp Gym App
# Automatically updates dependencies for security and performance
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # npm/pnpm dependencies for React + TypeScript + Capacitor
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "DavElizG"
    assignees:
      - "DavElizG"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Group React-related updates together
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      capacitor:
        patterns:
          - "@capacitor/*"
      vite:
        patterns:
          - "vite*"
          - "@vitejs/*"
      eslint:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "typescript-eslint"

  # GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "DavElizG"
    assignees:
      - "DavElizG"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"
 
